name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch (adjust as needed)
    paths:
      - '**/Dockerfile'  # Trigger only if the Dockerfile or related files are modified

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      packages: write  # Required to push to GitHub Packages
      contents: read   # Required to read the repository

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
          ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}
        labels: |
          org.opencontainers.image.title=Fluentd
          org.opencontainers.image.description=Fluentd custom image
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
        platforms: linux/amd64

    - name: Verify Image on GitHub Packages
      run: |
        echo "Listing images in GitHub Packages:"
        curl -u ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} https://ghcr.io/v2/${{ github.repository_owner }}/${{ github.event.repository.name }}/tags/list
